subgraphs:
    city:
        routing_url: http://localhost:4001/graphql
        schema:
            file: ../city/city.graphql
    weather:
        routing_url: http://localhost:4002/graphql
        schema:
            file: ../weather/weather.graphql
